### ISSUE TITLE
Getting notification when a tag is added?

### ISSUE THREAD

**Issue by hajoki** [Daniel-KM/Omeka-S-module-Folksonomy#1]
Hello, thank you for your great work!
Would it be possible to get a notification when a user adds a tag waiting for validation?

**Comment by Daniel-KM** [comment]
Thanks. 

What type of notifi cation? An email? A message in the admin board? Normally the reviewer or the editor has to go regularly on the admin side and check it.  

There is no notification system in Omeka, even for the jobs. Perhaps it may be a larger need.

**Comment by hajoki** [comment]
Thank you for clarifying this about the general functioning of Omeka, checking times to times sounds a reasonable solution.

**Comment by Daniel-KM** [comment]
I added a notification mail for public tagging on last release.
