### ISSUE TITLE
Folksonomy doesn't allow to use tag with quotes Omeka S Module

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-Folksonomy#4]
When you edit an item and you try to get tags from the right panel (Folksonomy), this is not possible if the tag contains single quotes (I suppose the same issue with some other special characters).

**Comment by Daniel-KM** [comment]
Ok, you find where I am. I don't have such issue. What is your tag?

**Comment by Daniel-KM** [comment]
In fact, there are forbidden character to avoid issues and hack (see https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/blob/7d61584f19335b2a32892467281ef8b5aed47afc/src/Api/Adapter/TagAdapter.php#L265). 

So `({})\/?<>*%|"`&;#+^$` are forbidden. It may be too restrictive, but single quote are allowed.

**Comment by Falteri** [comment]
Finally! It takes a long time, but I found you in the right place!

_________________________________________________
Simone Falteri
Technical Manager
s.falteri@ifnet.it
+39 055 0881306
+39 335 7871641

Ifnet srl an OCLC company - Firenze
Servizi per biblioteche e centri di documentazione
viale dei Mille, 164 - 50131 Firenze
Tel. +39 055 5001357
Fax +39 055 5001363
www.ifnet.it


_________________________________________________
AVVERTENZA: La presente comunicazione è confidenziale nonché tutelata dal
segreto professionale ed è comunque ad esclusivo uso del destinatario sopra
indicato. Nel caso non fosse destinata a Voi, Vi preghiamo di volerci
avvertire immediatamente tramite telefono o e-mail all’indirizzo sopra
indicato e distruggere quanto ricevuto. Grazie.
NOTICE: The information contained in this e-mail message is attorney-client
privileged and confidential, intended only for the use of the individual or
entity named above. If you are not the intended recipient, please notify us
immediately by telephone or e-mail and destroy this communication. Thank
you.

2018-01-25 7:55 GMT+01:00 Daniel Berthereau <notifications@github.com>:

**Comment by Falteri** [comment]
I see the code row you mention does not exclude the usage of single quote.
It seems to be an errore related with javascript

![immagine](https://user-images.githubusercontent.com/5129066/35395198-f7642b62-01e9-11e8-8533-0be30bedef70.png)

**Comment by Daniel-KM** [comment]
I think I fixed it with last git version.

**Comment by Falteri** [comment]
I will check. Thanks

**Comment by Falteri** [comment]
It doesn't seem to work yet.

**Comment by Falteri** [comment]
I think something like this should fix it:

if ($('#resource-tags').find('input[value="' + tagName.replace(/"/g, '\"')**.replace(/'/g, "\'")** + '"]').length) {

**Comment by Daniel-KM** [comment]
Your replace a single quote by a single quote, so it doesn't make sense. Can I have the tag that makes the issue?

**Comment by Falteri** [comment]
I’ve tried that code and it works.
Anyway you can use any tags you want with a single quote (“Libro d’arte”, “Livre d'art”, “film d'amour”, etc...).

Inviato da iPhone

**Comment by Falteri** [comment]
Sorry, pasting the code it lost "\".
The is the code:
if ($('#resource-tags').find('input[value="' + tagName.replace(/"/g, '\"').replace(/'/g, "\'") + '"]').length) {

Anyway you can use any tags you want with a single quote (“Libro d’arte”, “Livre d'art”, “film d'amour”, etc...).

**Comment by Daniel-KM** [comment]
I committed your change, but not sure if it can help.
