### ISSUE TITLE
import tags from a csv import

### ISSUE THREAD

**Issue by oupala** [Daniel-KM/Omeka-S-module-Folksonomy#5]
I'm using csv import to import data in omeka S.

The import goes well but I'm unable to import tags along with other data (from dublin core taxonomy).

How should I do this?

**Comment by Daniel-KM** [comment]
In less than one month.

**Comment by oupala** [comment]
Ok, do not hesitate to ping me here when it's ready.

**Comment by oupala** [comment]
The next release seems to be a bit late. Am I right?

**Comment by Daniel-KM** [comment]
Yes,  if finished some more urgent work, so now it's for the beginning of May.

**Comment by Daniel-KM** [comment]
Nevertheless, it's relatively simple to import a csv via sql in phpmyadmin or adminer.

**Comment by oupala** [comment]
The next release seems to be a bit late again. Am I right?

Any idea about when the release should be ready?

**Comment by Daniel-KM** [comment]
The first part of the rewrite and of the normalization is done with the module Annotate : https://github.com/Daniel-KM/Omeka-S-module-Annotate. The specific interface to quick tag and to upgrade Folksonomy is not published yet. 
Because tags are standards resources now, the csv import classes can be done easily now.

**Comment by Daniel-KM** [comment]
To display tags on front page, you can add a block of tags in any site page. For the second question, I don't understand. When you click a tag, the list of the resource with the same tags are displayed.

**Comment by chaudv** [comment]
Thanks for quick reply, Daniel. I screenshot here the block of tags appeared on front page. They are not link able 
![tags](https://user-images.githubusercontent.com/39289310/40047461-bdfdadd2-5859-11e8-959b-3ab295d14c76.jpg)

**Comment by Daniel-KM** [comment]
It can be edited via the theme, I didn't set options for the main page s/mysite/tags. So the term is not a link, but the numbers are links (normally with icons) (for item sets, item and media).
Nevertheless, to get the link on the term, you can create a site page block for tag cloud, where you can specify it.

**Comment by oupala** [comment]
@Daniel-KM As far as I understand, it is possible to create and edit tags:

> Annotations can be created via the tab "Annotations" of each resource (item sets, items and media). They can be browsed and managed via the main admin menu (admin/annotation).

But it is not yet possible to import tags from a csv file.

Am I right?

If yes, will this feature be implemented in a near futur? If yes, do you know when (approximately) and in which module?

**Comment by Daniel-KM** [comment]
You right, it is not yet possible to import tags by csv. But I didn't want to develop a feature that were needed to be upgraded, so I prefered to normalize the tags first (they are standard w3c annotations now), and folksonomy will be a simple module to display the specific form and the cloud. Development for this feature is used to be out of time, because the work for my paid customers come first. One of them wants annotations, so it will be done, but it is a long project, with many more modules, so I don't manage the priorities. I have to update the exiting tags to the new format too.

Here is a sql to import a list of tags:

```sql
INSERT INTO `tag` (`name`) VALUES
('alpha'),
('beta'),
('gamma'),
('delta');
```

Then the taggings, here for the resource #10432 (you should check that the tags and resource ids exists before, the owner id can be null):

```sql
INSERT INTO `tagging` (`status`, `tag_id`, `resource_id`, `owner_id`, `created`) VALUES
('proposed',  (SELECT id FROM tag WHERE name = 'alpha2'), 10432, 1, NOW()),
('allowed',  (SELECT id FROM tag WHERE name = 'beta2'), 10432, 1, NOW()),
('approved', (SELECT id FROM tag WHERE name = 'gamma2'), 10432, 1, NOW()),
('rejected', (SELECT id FROM tag WHERE name = 'delta2'), 10432, 1, NOW());
```

**Comment by Daniel-KM** [comment]
For annotations, the format of the csv file will be: 

```csv
Identifier, Resource Type, Annotation identifier, oa:hasSource, oa:motivatedBy, oa:hasPurpose, rdf:value
annotation#1, Annotation,, 10432, describing, tagging, My tag
```

**Comment by oupala** [comment]
Will annotations replace tags?

I mean, I don't clearly understand what we will have to do in order to support tags in Omeka S. Will they be supported without any module? Do we have to add the `Annotate` module? Will the `Annotate` module replace the  `Folksonomy` module?

I completely understand that you want to develop module for long, an a strong basis. I just lack a vision on how would be the solution at the end.

**Comment by Daniel-KM** [comment]
Annotate is a base module to manage w3c annotations. It works already, but the forms are too generic. Folksonomy will be a dependant module with quick forms, the manual validation, and the tag cloud. In fact, the interface will be the same, but the metadata will be saved differently. The existing tags will be converted automatically.

**Comment by oupala** [comment]
If I want to add tag management to my Omeka now, what would you suggest to me?

I have Annotate version 3.0.0 and Folksonomy version 3.3.7 available. Should I install one of them, two of them?

If I want to import tags and to insert tag manually by sql, with an insert into `tag` and `tagging` table, is that linked to Annotate or to Folksonomy?

DO you have an idea when the new version of Folksonomy will be available?

Thanks for your help and your patience.

**Comment by Daniel-KM** [comment]
It's simpler to continue to use Folksonomy alone. The tags will be upgraded automatically when ready. When ready, Folksonomy will be a sub-module of Annotate. Currently, they are totally separated.

**Comment by oupala** [comment]
Ok @Daniel-KM I'll use Folksonomy for the moment.

So I'd like to manually import tags into Folksonomy tables, by sql. Can you please confirm me that the tips you give me in [this comment](/Daniel-KM/Omeka-S-module-Folksonomy/issues/5#issuecomment-390599921) are convenient for Folksonomy module?

**Comment by Daniel-KM** [comment]
Yes, this is for the Folksonomy module.

**Comment by oupala** [comment]
@Daniel-KM The [comment where you indicate how to manually insert tags using sql ](/Daniel-KM/Omeka-S-module-Folksonomy/issues/5#issuecomment-390599921) might be very helpful but my problem is that I don't know the *resource id* of my resources.

As I imported my data from a csv file, I only know the resource id mentionned in the csv file, which is imported as `dcterms:identifier`.

So my question is: what sql subrequest can allors me to find the `resource id` based on `dcterms:identifier` of a resource?

**Comment by Daniel-KM** [comment]
The module was updated (v 3.3.8) to allow import via csv import (dev version, to install https://github.com/Daniel-KM/Omeka-S-module-CSVImport/releases). This is not yet integrated inside Annotate, but the interface and the import will be the same and tags will be upgraded automatically.

**Comment by oupala** [comment]
Thanks @Daniel-KM for this update. Unfortunately, I'm afraid I'm not sure how to test that.

First, I think that I will have to update my modules to [Omeka-S-module-Folksonomy dev release](https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/releases/tag/untagged-4bff28963e9f05068b0e) and to [Omeka-S-module-CSVImport forked from omeka-s-modules/CSVImport dev release](https://github.com/Daniel-KM/Omeka-S-module-CSVImport/releases).

The problem is that I also want to use sideload, which only works when using the upstream version of [CSVImport](https://github.com/omeka-s-modules/CSVImport/releases) (as far as I know). Maybe you have resynced your fork to the upstream version.

By the way, why are you forking this module instead of contributing to the upstream one. I think you must have a good reason for doing so, can you tell it to us?

**Comment by Daniel-KM** [comment]
The upgrade of modules Sideload and Mapping are available too : https://github.com/Daniel-KM/Omeka-S-module-FileSideload/releases and https://github.com/Daniel-KM/Omeka-S-module-mapping.

The feature are currently pushed upstream for review. They will be integrated soon. Test it and add some comments, for example about the new ui (that should be simple but efficient), on https://github.com/omeka-s-modules/CSVImport/pull/105.

**Comment by Daniel-KM** [comment]
Note that are new upgrades of the ui in the upstream dev version, so it may change again.

**Comment by oupala** [comment]
@Daniel-KM Do you mean that you develop into [Daniel-KM/Omeka-S-module-FileSideload](https://github.com/Daniel-KM/Omeka-S-module-FileSideload) then ask for validation, then merge it into [omeka-s-modules/FileSideload](https://github.com/omeka-s-modules/FileSideload)?

And same process for every module your contributing?

**Comment by Daniel-KM** [comment]
This is the normal process for the development on github. I don't have write access to FileSideload neither any of the Omeka repositories, so I fork it, fix it and ask a pull request (I don't want to maintain a fork). All my improvements will be integrated upstream. To get them integrated quickly, don't hesitate to add a comment on each pull request.

**Comment by Daniel-KM** [comment]
Annotate and Folksonomy are modules I build for a project, they are not created by the Omeka team. My pull requests are for CsvImport (omeka-s-modules/CSVImport#105) and FileSideload (https://github.com/omeka-s-modules/FileSideload/pull/13). Note that if some requests are not accepted (everyone has their own priorities), normally I will be able to maintain a small module for the features I need (advanced automapping in particular).

**Comment by oupala** [comment]
I commented both merge requests.

For Annotate and Folksonomy, will you also update [Omeka-S modules page](https://omeka.org/s/modules/)?

**Comment by Daniel-KM** [comment]
I have already send some modules. Folksonomy will be released automatically on omeka.org page in some time, but the last version is not compatible with the last stable version of csv import, so I should wait. Annotate is still under development for some weeks.

**Comment by oupala** [comment]
I sent some comments on the pull request you made, but no one seems to respond. Is everything healthy around Omeka-S and the team managing it?

**Comment by Daniel-KM** [comment]
Yes, Omeka is healthy, but the priorities are managed by the ones who order... Perhaps the Omeka team work on modules that will be released soon, or a new feature for the core, etc. 
Note that my changes are already merged in the dev branch of Csv Import, so you can already use it. And it's stable enough.

**Comment by oupala** [comment]
Ok, thanks for the informations.

I just have to understand how I can use and install a develop branch of a module... And when this develop branch will be released as a final release?

**Comment by Daniel-KM** [comment]
There is a button "branch" in the top left of each repository. It seems that by default, it is the branch develop one for Csv Import. But there is no zip package for it, so you have to have a dev environment to fetch the dependencies, as indicated in the readme. 

For my fork, the default branch is master, but I published a zip package (https://github.com/Daniel-KM/Omeka-S-module-CSVImport/releases).

I didn't tested Folksonomy with the dev branch of the Omeka team, but it works with mine. So in the short time, it's simpler to take it.

**Comment by oupala** [comment]
As far as I understand, the *official* release of Folksonomy is version 3.3.7 (see [official website of Omeka S](https://omeka.org/s/modules/Folksonomy/). This version does not yet allow importing tags using the CSV Import module.

Your are developing a new release of this module on this repository, whose version is 3.3.8 or maybe 3.3.9 (see the [release page](https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/releases). But this version is not yet available on the official repository.

Do you have any idea when the version that allows importing tags will be available in the official repository?

Sorry if I have misunderstood anything, but it's hard for me to understand each release cycle and all dependencies relationships.
