### ISSUE TITLE
Tag Cloud displays every single tag throughout sites - can they be limited to each site as an option? 

### ISSUE THREAD

**Issue by GitByrd** [Daniel-KM/Omeka-S-module-Folksonomy#9]
More like a suggestion that would be really helpful....Can there be a way to add an option to only display a tag cloud with tags associated with a certain site and not across every single site?  We have separate sites created by student class projects, and they only want to display their items' tags in a cloud on their site...

Thanks!

**Comment by Daniel-KM** [comment]
Yes, it will be available in the next version (not the 3.3, but the next one).

**Comment by Daniel-KM** [comment]
Implemented in version 3.3.11.
